# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed
spec:
  selector:
    matchLabels:
      run: feed
  replicas: 2
  template:
    metadata:
      labels:
        run: feed
    spec:
      containers:
        - name: feed
          image: docker.io/ja50n/udagram-api-feed:v1
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '1024Mi'
              cpu: '500m'

# Service
apiVersion: v1
kind: Service
metadata:
  labels:
    service: feed
  name: feed
spec:
  ports:
    - name: '8080'
      port: 8080
      targetPort: 8080
  selector:
    service: feed
