apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    service: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      service: frontend
      api: external
  template:
    metadata:
      labels:
        service: frontend
        api: external
    spec:
      containers:
        - image: docker.io/ja50n/udagram-frontend:v1
          name: frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '1024Mi'
              cpu: '500m'
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    run: frontend
spec:
  ports:
    - name: '8100'
      port: 8100
      targetPort: 80
  selector:
    service: frontend
